[[redirects]]
from = "2-cimento-todas-as-obras-votoran-50-kg.html"
to = "/cimento-votoran-todas-as-obras-50-kg"
status = 301

[[redirects]]
from = "388-cimento-cp-iv-32-rs-caue-50-kg.html"
to = "/cimento-caue-50-kg"
status = 301

[[redirects]]
from = "15-cal-para-pintura-5-kg-tancal.html"
to = "/cal-para-pintura-tancal"
status = 301

[[redirects]]
from = "14-cal-virgem-comum-20-kg-tancal.html"
to = "/cal-virgem-comum-tancal"
status = 301

[[redirects]]
from = "13-cal-hidratada-tancal-20-kg.html"
to = "/cal-hidratada-tancal"
status = 301

[[redirects]]
from = "10-argamassa-colante-interna-aci-20-kg-votoran.html"
to = "/argamassa-colante-interna-aci-votoran"
status = 301

[[redirects]]
from = "12-arg
amassa-colante-piso-sobre-piso-cinza-20-kg-votoran.html"
to = "/argamassa-colante-piso-sobre-piso-e-porcelanatos-cinza-votoran"
status = 301

[[redirects]]
from = "11-argamassa-colante-externa-acii-20-kg-votoran.html"
to = "/argamassa-colante-externa-acii-votoran"
status = 301

[[redirects]]
from = "16-argamassa-pronta-unica-20kg-votoran.html"
to = "/argamassa-pronta-para-reboco-e-assentamento-votoran"
status = 301
