[build]
  command = "echo 'pre-rendered'"
  
[[redirects]]
from = "/2-cimento-todas-as-obras-votoran-50-kg.html"
to = "/cimento-votoran-todas-as-obras-50-kg"
status = 301

[[redirects]]
from = "/388-cimento-cp-iv-32-rs-caue-50-kg.html"
to = "/cimento-caue-50-kg"
status = 301

[[redirects]]
from = "/15-cal-para-pintura-5-kg-tancal.html"
to = "/cal-para-pintura-tancal"
status = 301

[[redirects]]
from = "/14-cal-virgem-comum-20-kg-tancal.html"
to = "/cal-virgem-comum-tancal"
status = 301

[[redirects]]
from = "/13-cal-hidratada-tancal-20-kg.html"
to = "/cal-hidratada-tancal"
status = 301

[[redirects]]
from = "/10-argamassa-colante-interna-aci-20-kg-votoran.html"
to = "/argamassa-colante-interna-aci-votoran"
status = 301

[[redirects]]
from = "/12-argamassa-colante-piso-sobre-piso-cinza-20-kg-votoran.html"
to = "/argamassa-colante-piso-sobre-piso-e-porcelanatos-cinza-votoran"
status = 301

[[redirects]]
from = "/11-argamassa-colante-externa-acii-20-kg-votoran.html"
to = "/argamassa-colante-externa-acii-votoran"
status = 301

[[redirects]]
from = "/16-argamassa-pronta-unica-20kg-votoran.html"
to = "/argamassa-pronta-para-reboco-e-assentamento-votoran"
status = 301

[[redirects]]
from = "/25-po-de-brita-m.html"
to = "/po-de-brita"
status = 301

[[redirects]]
from = "/22-brita01agg5rosadam3.html"
to = "/brita-rosada"
status = 301

[[redirects]]
from = "/47-tijolo-21-furos-mesclado-santa-fe.html"
to = "/tijolo-21-furos-mesclado-santa-fe"
status = 301

[[redirects]]
from = "/46-tijolo-refratario-229x114x25-tijoleta.html"
to = "/tijolo-refratario-fino"
status = 301

[[redirects]]
from = "/18-areiao-grosso-m.html"
to = "/areiao-grosso"
status = 301

[[redirects]]
from = "/34-pedra-gres-grossa-42cm-x-22cm-x-17cm-unidade.html"
to = "/pedra-gres-grossa-17cm"
status = 301

[[redirects]]
from = "/42-tijolo-6-furos-9-x-14-x-19-cm.html"
to = "/tijolo-6-furos-19cm"
status = 301

[[redirects]]
from = "/41-tijolo-6-furos-9-x-14-x-24-cm.html"
to = "/tijolo-6-furos-24cm"
status = 301

[[redirects]]
from = "/290-tubo-para-drenagem-corrugado-pead-preto-4-polegadas-metasul.html"
to = "/tubo-para-drenagem"
status = 301

[[redirects]]
from = "/20-areia-media-m.html"
to = "/areia-media"
status = 301

[[redirects]]
from = "/13-cal-hidratada-tancal-20-kg.html"
to = "/cal-hidratada-tancal"
status = 301

[[redirects]]
from = "/contato"
to = "/pages/contato"
status = 301

[[redirects]]
from = "/175-mascara-semi-facial-pff2-com-valvula-atlas.html"
to = "/"
status = 301

[[redirects]]
from = "/357-arandela-colonial-externa-pendente-para-teto-preta-de-aluminio-tlf-28-taschibra.html"
to = "/"
status = 301

[[redirects]]
from = "/37-material_de_construcao"
to = "/material-de-construcao"
status = 301

[[redirects]]
from = "/37-tijoleta-gres-unidade.html"
to = "/"
status = 301

[[redirects]]
from = "/43-tijolo-refratario-229x114x51-15-furos.html"
to = "/tijolo-refratario-15-furos-grosso"
status = 301

[[redirects]]
from = "/40-tijolo-macico-5-cm-x-9-cm-x-24-cm.html"
to = "/tijolo-macico"
status = 301

[[redirects]]
from = "/48-tijolo-21-furos-vermelho-santa-fe.html"
to = "/tijolo-21-furos-vermelho-santa-fe"
status = 301

[[redirects]]
from = "/52-duchas-e-chuveiros"
to = "/duchas-e-chuveiros"
status = 301

[[redirects]]
from = "/33-malha-de-ferro-15cm-x-15cm-2m-3m.html"
to = "/malha-de-ferro-4-2mm-15cm-x-15cm-2m-x-3m"
status = 301

[[redirects]]
from = "24-brita-m.html"
to = "/brita-1"
status = 301

[[redirects]]
from = "/335-serra-tico-tico-550w-220v-black-decker.html"
to = "/"
status = 301

[[redirects]]
from = "/44-tijolo-refratario-229x114x51.html"
to = "/tijolo-refratario-grosso"
status = 301

[[redirects]]
from = "/8-tijolo"
to = "/tijolo"
status = 301

[[redirects]]
from = "/28-ferro-gerdau-10mm-12-metros.html"
to = "/ferro-gerdau-10-mm-12-metros"
status = 301

[[redirects]]
from = "/29-ferro-gerdau-8mm-12-metros.html"
to = "/ferro-gerdau-8-mm-12-metros"
status = 301

[[redirects]]
from = "/30-ferro-gerdau-6-3-mm-12-metros.html"
to = "/ferro-gerdau-6-3-mm-12-metros"
status = 301

[[redirects]]
from = "/6-ferro"
to = "/ferro"
status = 301

[[redirects]]
from = "/76-tintas-e-pintura"
to = "/tintas-e-pintura"
status = 301

[[redirects]]
from = "/262-nivel-de-aluminio-120cm-48-stanley.html"
to = "/"
status = 301

[[redirects]]
from = "/32-ferro-gerdau-4-2mm-12-metros.html"
to = "/ferro-gerdau-4-2-mm-12-metros"
status = 301

[[redirects]]
from = "/338-jimo-antitraca-em-cartela-cabide.html"
to = "/"
status = 301

[[redirects]]
from = "/49-adesivo-selante-cristal-50g-mixbond.html"
to = "/"
status = 301

[[redirects]]
from = "/204-chaleira-preta-inox-25-litros-mattina-mor.html"
to = "/"
status = 301

[[redirects]]
from = "/27-ferro-gerdau-12-5mm-12-metros.html"
to = "/ferro-gerdau-12-5-mm-12-metros"
status = 301

[[redirects]]
from = "/38-vedacao-e-impermeabilizacao"
to = "/vedacao-e-impermeabilizacao"
status = 301

[[redirects]]
from = "/4-cimento-cal-e-argamassas"
to = "/cimento-cal-e-argamassas"
status = 301

[[redirects]]
from = "/91-ducha-sublime-zagonel-220v-7500w.html"
to = "/"
status = 301

[[redirects]]
from = "/23-brita-04-pedrisco-m.html"
to = "/brita-04"
status = 301

[[redirects]]
from = "/39-material-hidraulico"
to = "/material-hidraulico"
status = 301

[[redirects]]
from = "/98-pisos-e-revestimentos"
to = "/revestimentos"
status = 301

[[redirects]]
from = "/359-ducha-top-jet-turbo-eletronica-7500w-220v-lorenzetti.html"
to = "/"
status = 301

[[redirects]]
from = "/36-pedra-gres-media-42cm-x-22cm-x-14cm-unidade.html"
to = "/pedra-gres-media-14cm"
status = 301

[[redirects]]
from = "/31-ferro-gerdau-5mm-12-metros.html"
to = "/ferro-gerdau-5-mm-12-metros"
status = 301

[[redirects]]
from = "/7-pedra-gres"
to = "/pedra-gres"
status = 301

[[redirects]]
from = "/5-areia-e-brita"
to = "/areia-e-brita"
status = 301

[[redirects]]
from = "/45-tijolo-refratario-229x114x44.html"
to = "/tijolo-refratario-medio"
status = 301

[[redirects]]
from = "/305-manta-geotextil-215-metros.html"
to = "/manta-geotextil-para-drenagem"
status = 301
