name: Setup Firebase CI

on:
  push:
    branches:
      - master
    paths:
      - '.github/setup-firebase-ci'

jobs:
  setup-firebase-ci:
    name: Fix repository workflows for Firebase deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check Firebase credentials secrets
        env:
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        if: env.FIREBASE_PRIVATE_KEY == null
        run: exit 1

      - name: Set remote repo URL
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=url::https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        id: remote_repo

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare CI files for Firebase
        run: |
          rm -rf ./.isg ./.bundles.json ./.github/workflows/setup-firebase-ci.yml
          sed -i 's/.netlify\/functions\/ssr/functions/' ./.dependabot/config.yml
          mv ./.github/workflows/.firebase/build-and-deploy.yml ./.github/workflows/build-and-deploy.yml

      - name: Config Git and commit
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add -A
          git commit -m "ci(firebase): prepare workflows for firebase deploy [skip ci]"

      - name: Push changes
        env:
          REMOTE_REPO: ${{ steps.remote_repo.outputs.url }}
        run: git push "${REMOTE_REPO}" HEAD:master

      - name: Delete dist to clear Git ref
        continue-on-error: true
        env:
          REMOTE_REPO: ${{ steps.remote_repo.outputs.url }}
        run: git push "${REMOTE_REPO}" --delete dist
